spring:
  application:
    name: restartTwo


  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/tlias?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: D42GSLfbJRnARmv.root
    password: 1ML8wfzncQU0PlEC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug